### ISSUE TITLE
Remove MMTK_PLAN and THIRD_PARTY_HEAP_LIMIT

### ISSUE THREAD

**Issue by chrisseaton** [mmtk/mmtk-ruby#15]
We don't need to support these environment variables anymore now we have the flags, do we? Ruby lets you set options using the `RUBYOPT` environment variable, so they're not even needed to set globally.

**Comment by wks** [comment]
That's right.  As we discussed in another issue (https://github.com/mmtk/mmtk-core/issues/636), we will eventually remove the ability to set options via `MMTK_xxxx` environment variables.

Keeping RUBYOPT is important, as it is necessary for setting MMTk plans for `make btest`.
